### ISSUE TITLE
Installing typing breaks jupyterlab

### ISSUE THREAD

**Issue by dhirschfeld** [AnacondaRecipes/typing-feedstock#2]
After installing typing JupyterLab can't start any kernels, instead giving the below error:
```python-traceback
[I 11:16:01.218 LabApp] Kernel started: 92e38a58-7f15-441f-9b52-f06e9cbedc23
Traceback (most recent call last):
  File "C:/Users/dhirschf/envs/dev/Lib/site-packages/ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "C:\Users\dhirschf\envs\dev\Lib\site-packages\ipykernel\__init__.py", line 2, in <module>
    from .connect import *
  File "C:\Users\dhirschf\envs\dev\Lib\site-packages\ipykernel\connect.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
  File "C:\Users\dhirschf\envs\dev\Lib\site-packages\IPython\__init__.py", line 55, in <module>
    from .terminal.embed import embed
  File "C:\Users\dhirschf\envs\dev\Lib\site-packages\IPython\terminal\embed.py", line 14, in <module>
    from IPython.core.magic import Magics, magics_class, line_magic
  File "C:\Users\dhirschf\envs\dev\Lib\site-packages\IPython\core\magic.py", line 22, in <module>
    from IPython.core.inputtransformer2 import ESC_MAGIC, ESC_MAGIC2
  File "C:\Users\dhirschf\envs\dev\Lib\site-packages\IPython\core\inputtransformer2.py", line 16, in <module>
    from typing import List, Tuple, Union
  File "C:\Users\dhirschf\envs\dev\Lib\site-packages\typing.py", line 1347, in <module>
    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
  File "C:\Users\dhirschf\envs\dev\Lib\site-packages\typing.py", line 1003, in __new__
    self._abc_registry = extra._abc_registry
AttributeError: type object 'Callable' has no attribute '_abc_registry'
```

I'm on win64, py37. ` typing-3.6.4-py37_0`

**Comment by dhirschfeld** [comment]
Why is typing even built/installed for py37? I thought it was a backport for py<36?

**Comment by dhirschfeld** [comment]
Fixed by https://github.com/conda-forge/promise-feedstock/pull/7
